////
 README.adoc
-------------------------------------------------------------------------------
   Copyright 2017 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= Welcome to the CloudForms Essentials Project

This project was designed to augment Red Hat (R) https://www.redhat.com/en/technologies/cloud-computing/cloudforms[CloudForms]
installations.

CloudForms version: link:https://github.com/ramrexx/CloudForms_Essentials/tree/cf4.5[CloudForms 4.5]

== Installation Instructions


=== Clone this repository

This repo is required in order to import some of the items referenced on this page.

.  While in `root's` home directory, clone the cfme-rhconsulting-scripts repo:

 git clone -b cf4.5 https://github.com/ramrexx/CloudForms_Essentials

.  Change directory to `/root/CloudForms_Essentials` directory:

 cd /root/CloudForms_Essentials




<<top>>

=== Clone cfme-rhconsulting-scripts repository

This repo is required in order to import some of the items referenced on this page.

.  While in `root's` home directory, clone the cfme-rhconsulting-scripts repo:

 git clone https://github.com/rhtconsulting/cfme-rhconsulting-scripts

.  Change directory to `/root/rhtconsulting-cfme-rhconsulting-scripts` directory:

 cd /root/rhtconsulting-cfme-rhconsulting-scripts

.  Install import/export utilities

 make clean install

You can ignore the "/bin/sh: rpmbuild: command not found" warning message

The `/usr/bin/miqimport` and `/usr/bin/miqexport` utilities are now installed

<<top>>